---

# This check fails if Redis is present in the new build's Gemfile but Redis is not installed yet,
# which will block the deployment from proceeding (until the server is correctly provisioned).

- name: gather host services facts
  service_facts:

- name: check redis presence in gemfile
  lineinfile:
    dest: "{{ build_path }}/Gemfile"
    regex: "^gem .*redis"
    state: absent
  check_mode: yes # Don't actually modify the file
  become: yes
  register: redis_requirement
  ignore_errors: true

- name: stop deployment if redis is both required and absent
  fail:
    msg: |
      The deployed OFN version requires Redis to be installed.
      Please provision with the latest copy of ofn-install before deploying.
  when: "redis_requirement is changed and 'redis-server.service' not in services"
